set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
set(CMAKE_LIBRARY_ARCHITECTURE arm-linux-gnueabihf)
set(CMAKE_INCLUDE_PATH /usr/arm-linux-gnueabihf/include;/usr/include/arm-linux-gnueabihf;/usr/include)
set(ENV{JAVA_HOME} /usr/lib/jvm/java-11-openjdk-armhf)
