# TCL File Generated by Component Editor 20.1
# Wed Nov 03 14:17:28 CDT 2021
# DO NOT MODIFY


# 
# button_controller "Button Controller" v1.0
#  2021.11.03.14:17:28
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module button_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME button_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Button Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL button_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file button_controller.v VERILOG PATH src/button_controller.v TOP_LEVEL_FILE
add_fileset_file clock_divider.v VERILOG PATH src/clock_divider.v

# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point buttons
# 
add_interface buttons conduit end
set_interface_property buttons associatedClock clk
set_interface_property buttons associatedReset reset
set_interface_property buttons ENABLED true
set_interface_property buttons EXPORT_OF ""
set_interface_property buttons PORT_NAME_MAP ""
set_interface_property buttons CMSIS_SVD_VARIABLES ""
set_interface_property buttons SVD_ADDRESS_GROUP ""

add_interface_port buttons buttons buttons Input 4
add_interface_port buttons switches switches Input 10


# 
# connection point irq
# 
add_interface irq conduit end
set_interface_property irq associatedClock clk
set_interface_property irq associatedReset reset
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq_buttons irq_buttons Output 4
add_interface_port irq irq_switches irq_switches Output 10

