# TCL File Generated by Component Editor 20.1
# Wed Nov 03 14:27:20 CDT 2021
# DO NOT MODIFY


# 
# interrupt_controller "Interrupt Controller" v1.0
#  2021.11.03.14:27:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module interrupt_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME interrupt_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Interrupt Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL interrupt_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file interrupt_controller.v VERILOG PATH src/interrupt_controller.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon
# 
add_interface avalon avalon end
set_interface_property avalon addressUnits WORDS
set_interface_property avalon associatedClock clk
set_interface_property avalon associatedReset reset
set_interface_property avalon bitsPerSymbol 8
set_interface_property avalon burstOnBurstBoundariesOnly false
set_interface_property avalon burstcountUnits WORDS
set_interface_property avalon explicitAddressSpan 0
set_interface_property avalon holdTime 0
set_interface_property avalon linewrapBursts false
set_interface_property avalon maximumPendingReadTransactions 0
set_interface_property avalon maximumPendingWriteTransactions 0
set_interface_property avalon readLatency 0
set_interface_property avalon readWaitTime 1
set_interface_property avalon setupTime 0
set_interface_property avalon timingUnits Cycles
set_interface_property avalon writeWaitTime 0
set_interface_property avalon ENABLED true
set_interface_property avalon EXPORT_OF ""
set_interface_property avalon PORT_NAME_MAP ""
set_interface_property avalon CMSIS_SVD_VARIABLES ""
set_interface_property avalon SVD_ADDRESS_GROUP ""

add_interface_port avalon address address Input 2
add_interface_port avalon readdata readdata Output 32
add_interface_port avalon writedata writedata Input 32
add_interface_port avalon write write Input 1
add_interface_port avalon byteenable byteenable Input 4
set_interface_assignment avalon embeddedsw.configuration.isFlash 0
set_interface_assignment avalon embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point irq_ps2
# 
add_interface irq_ps2 conduit end
set_interface_property irq_ps2 associatedClock clk
set_interface_property irq_ps2 associatedReset reset
set_interface_property irq_ps2 ENABLED true
set_interface_property irq_ps2 EXPORT_OF ""
set_interface_property irq_ps2 PORT_NAME_MAP ""
set_interface_property irq_ps2 CMSIS_SVD_VARIABLES ""
set_interface_property irq_ps2 SVD_ADDRESS_GROUP ""

add_interface_port irq_ps2 irq_ps2 irq_ps2 Input 1


# 
# connection point irq_buttons
# 
add_interface irq_buttons conduit end
set_interface_property irq_buttons associatedClock clk
set_interface_property irq_buttons associatedReset reset
set_interface_property irq_buttons ENABLED true
set_interface_property irq_buttons EXPORT_OF ""
set_interface_property irq_buttons PORT_NAME_MAP ""
set_interface_property irq_buttons CMSIS_SVD_VARIABLES ""
set_interface_property irq_buttons SVD_ADDRESS_GROUP ""

add_interface_port irq_buttons irq_buttons irq_buttons Input 4
add_interface_port irq_buttons irq_switches irq_switches Input 10

