# TCL File Generated by Component Editor 20.1
# Thu Dec 02 15:07:28 CST 2021
# DO NOT MODIFY


# 
# vga_translate "VGA TRANSLATE" v1.0
#  2021.12.02.15:07:28
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_translate
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_translate
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA TRANSLATE"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_translate
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file vga_translate.v VERILOG PATH src/vga_translate.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point mm_slave
# 
add_interface mm_slave avalon end
set_interface_property mm_slave addressUnits WORDS
set_interface_property mm_slave associatedClock clk
set_interface_property mm_slave associatedReset reset
set_interface_property mm_slave bitsPerSymbol 8
set_interface_property mm_slave burstOnBurstBoundariesOnly false
set_interface_property mm_slave burstcountUnits WORDS
set_interface_property mm_slave explicitAddressSpan 0
set_interface_property mm_slave holdTime 0
set_interface_property mm_slave linewrapBursts false
set_interface_property mm_slave maximumPendingReadTransactions 0
set_interface_property mm_slave maximumPendingWriteTransactions 0
set_interface_property mm_slave readLatency 0
set_interface_property mm_slave readWaitTime 1
set_interface_property mm_slave setupTime 0
set_interface_property mm_slave timingUnits Cycles
set_interface_property mm_slave writeWaitTime 0
set_interface_property mm_slave ENABLED true
set_interface_property mm_slave EXPORT_OF ""
set_interface_property mm_slave PORT_NAME_MAP ""
set_interface_property mm_slave CMSIS_SVD_VARIABLES ""
set_interface_property mm_slave SVD_ADDRESS_GROUP ""

add_interface_port mm_slave hps_write write Input 1
add_interface_port mm_slave hps_waitrequest waitrequest Output 1
add_interface_port mm_slave hps_writedata writedata Input 16
add_interface_port mm_slave hps_address address Input 19
add_interface_port mm_slave hps_byteenable byteenable Input 2
set_interface_assignment mm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment mm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point sdram_master
# 
add_interface sdram_master avalon start
set_interface_property sdram_master addressUnits SYMBOLS
set_interface_property sdram_master associatedClock clk
set_interface_property sdram_master associatedReset reset
set_interface_property sdram_master bitsPerSymbol 8
set_interface_property sdram_master burstOnBurstBoundariesOnly false
set_interface_property sdram_master burstcountUnits WORDS
set_interface_property sdram_master doStreamReads false
set_interface_property sdram_master doStreamWrites false
set_interface_property sdram_master holdTime 0
set_interface_property sdram_master linewrapBursts false
set_interface_property sdram_master maximumPendingReadTransactions 0
set_interface_property sdram_master maximumPendingWriteTransactions 0
set_interface_property sdram_master readLatency 0
set_interface_property sdram_master readWaitTime 1
set_interface_property sdram_master setupTime 0
set_interface_property sdram_master timingUnits Cycles
set_interface_property sdram_master writeWaitTime 0
set_interface_property sdram_master ENABLED true
set_interface_property sdram_master EXPORT_OF ""
set_interface_property sdram_master PORT_NAME_MAP ""
set_interface_property sdram_master CMSIS_SVD_VARIABLES ""
set_interface_property sdram_master SVD_ADDRESS_GROUP ""

add_interface_port sdram_master sdram_address address Output 32
add_interface_port sdram_master sdram_byteenable byteenable Output 2
add_interface_port sdram_master sdram_waitrequest waitrequest Input 1
add_interface_port sdram_master sdram_write write Output 1
add_interface_port sdram_master sdram_writedata writedata Output 16


# 
# connection point vga_master
# 
add_interface vga_master avalon start
set_interface_property vga_master addressUnits SYMBOLS
set_interface_property vga_master associatedClock clk
set_interface_property vga_master associatedReset reset
set_interface_property vga_master bitsPerSymbol 8
set_interface_property vga_master burstOnBurstBoundariesOnly false
set_interface_property vga_master burstcountUnits WORDS
set_interface_property vga_master doStreamReads false
set_interface_property vga_master doStreamWrites false
set_interface_property vga_master holdTime 0
set_interface_property vga_master linewrapBursts false
set_interface_property vga_master maximumPendingReadTransactions 0
set_interface_property vga_master maximumPendingWriteTransactions 0
set_interface_property vga_master readLatency 0
set_interface_property vga_master readWaitTime 1
set_interface_property vga_master setupTime 0
set_interface_property vga_master timingUnits Cycles
set_interface_property vga_master writeWaitTime 0
set_interface_property vga_master ENABLED true
set_interface_property vga_master EXPORT_OF ""
set_interface_property vga_master PORT_NAME_MAP ""
set_interface_property vga_master CMSIS_SVD_VARIABLES ""
set_interface_property vga_master SVD_ADDRESS_GROUP ""

add_interface_port vga_master vga_address address Output 4
add_interface_port vga_master vga_byteenable byteenable Output 4
add_interface_port vga_master vga_waitrequest waitrequest Input 1
add_interface_port vga_master vga_write write Output 1
add_interface_port vga_master vga_writedata writedata Output 32


# 
# connection point vga_frame_ctrl
# 
add_interface vga_frame_ctrl conduit end
set_interface_property vga_frame_ctrl associatedClock clk
set_interface_property vga_frame_ctrl associatedReset ""
set_interface_property vga_frame_ctrl ENABLED true
set_interface_property vga_frame_ctrl EXPORT_OF ""
set_interface_property vga_frame_ctrl PORT_NAME_MAP ""
set_interface_property vga_frame_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property vga_frame_ctrl SVD_ADDRESS_GROUP ""

add_interface_port vga_frame_ctrl frame_start frame_start Input 1
add_interface_port vga_frame_ctrl frame_hold frame_hold Input 1

